# Make CHOICE

!if $d(BEEP)
ASMFLAGS=/m /dBEEP
!else
ASMFLAGS=/m
!endif

ichoice.com: main.obj
             tlink /t /x main.obj,.\bin\choice.com
main.obj: main.asm gcmdl2.asm msg.inc
          tasm $(ASMFLAGS) main.asm
clean:
       del *.obj
